### ISSUE TITLE
where the train.py is stored?

### ISSUE THREAD

**Issue by xjtusjtu** [ikb-a/idk-dialogue-relevance#1]
Hello esteemed developers,

I am curious about the whereabouts of the train.py. Could you kindly direct me to the location where the script is stored or provide any relevant information on how to access it?

https://github.com/ikb-a/idk-dialogue-relevance/blob/5b7014f8149f3e03e7fe3c3fc0ca4468bcf9f93d/external_projects/NUP-BERT/usl_score/train_all.sh#L9

Your assistance would be greatly appreciated.

Best regards.

**Comment by ikb-a** [comment]
Yeah, no worries -- details are in the subdirectory's readme: https://github.com/ikb-a/idk-dialogue-relevance/blob/5b7014f8149f3e03e7fe3c3fc0ca4468bcf9f93d/external_projects/NUP-BERT/README.md

The specific commit is there, but I believe this should be the file you're looking for: https://github.com/vitouphy/usl_dialogue_metric/blob/2b2037e4d76a08925e47c506f1edc663072161e2/usl_score/train.py

Cheers!

**Comment by xjtusjtu** [comment]
Thank you so much! Now I get it.
